export const ActionTypes = Object.freeze({

    TIME_UPDATE:'TIME_UPDATE',

    USER_AUTH_REQUEST:'USER_AUTH_REQUEST',
    USER_AUTH_SUCCESS:'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE:'USER_AUTH_FAILURE',

    USER_LIST_GET:'USER_LIST_GET',
    USER_LIST_UPDATE:'USER_LIST_UPDATE',

    MESSAGE_LIST_GET:'MESSAGE_LIST_GET',
    MESSAGE_LIST_UPDATE:'MESSAGE_LIST_UPDATE',

    MESSAGE_SEND_REQUEST:'MESSAGE_SEND_REQUEST',
    MESSAGE_SEND_SUCCESS:'MESSAGE_SEND_SUCCESS',
    MESSAGE_SEND_FAILURE:'MESSAGE_SEND_FAILURE',

    SYSTEM_ERROR:'SYSTEM_ERROR'

});